### ISSUE TITLE
fix: add e2e tests for very_good_core

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_core#220]
As a developer, I want to have e2e tests running in the CI as part of very_good_core to ensure the brick is always functioning as expected (similar to e2e tests in very_good_cli).

**Comment by alestiago** [comment]
Thanks @felangel for this issue. I have some questions regarding it.

Q1. Where should the test file be included within `very_good_core`?
Q2. Would we like to unit test the `GeneratorStringX` and `pre_gen` hook?

**Comment by renancaraujo** [comment]
Closing due to [this](https://github.com/VeryGoodOpenSource/very_good_core/pull/247#issuecomment-1478238810)
