### ISSUE TITLE
docs: Missing l10n documentation in the flutter project's `readme.md`

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_core#259]
> **Note**: This [issue](https://github.com/VeryGoodOpenSource/very_good_cli/issues/691) was originally opened at [Very Good Cli](https://github.com/VeryGoodOpenSource/very_good_cli) by @tanmoy27112000.

## Description
The command to generate the new Localizations class when new strings are added to the arb file is missing.

## Steps To Reproduce

1. Create a flutter project using the cli
2. Check the `README.md` file

**Expected Behavior:**
The documentation should contain the command that has to be used to generate the classes for locale.

```sh
flutter gen-l10n
```

**Comment by RobertPietraru** [comment]
I created a pull request for this issue:
https://github.com/VeryGoodOpenSource/very_good_core/pull/275
