### ISSUE TITLE
bug: Podfile does not find the RunnerTests directory

### ISSUE THREAD

**Issue by yuruyuri16** [VeryGoodOpenSource/very_good_core#279]
**Description**

After upgrading flutter to the latest version. Every time I run the project there is a new error because the Podfile generated expects for a `RunnerTests/` directory to be inside `/ios`.

**Steps To Reproduce**

1. Run your app
2. Error appears

**Expected Behavior**
The app should run normally.

**Error**

```
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    [!] Unable to find a target named `RunnerTests` in project `Runner.xcodeproj`, did find `Runner`.
```

**Comment by renancaraujo** [comment]
Fixed on https://github.com/VeryGoodOpenSource/very_good_core/pull/285
