### ISSUE TITLE
fix: add build folder in .gitignore of the starter app

### ISSUE THREAD

**Issue by superiorsd10** [VeryGoodOpenSource/very_good_core#293]
**Description**
Currently, when we create a flutter app using `very_good_cli`, it doesn't include the `build` folder in the `.gitignore` file. There is no need to push the `build` folder to the respective `GitHub` repository of the project. So it'll be good to add the `build` in the `.gitignore` file of the project. 

**Expected Behavior**
The `build` folder should be in the `.gitignore` file already when the project is created, so the user doesn't have to manually add it. 

**Screenshots**
![SCR-20230928-jwy](https://github.com/VeryGoodOpenSource/very_good_core/assets/92971894/1f1dceec-7013-4458-800d-fce4805c8ab8)

**Comment by superiorsd10** [comment]
Hello, 
I'd like to contribute to the `very_good_core`. Would it be possible to assign this issue to me? I'd be happy to work on it.

Thank you,

**Comment by renancaraujo** [comment]
Hey @superiorsd10 seems like the build dir [is indeed ignore by the brick](https://github.com/VeryGoodOpenSource/very_good_core/blob/main/brick/__brick__/%7B%7Bproject_name.snakeCase()%7D%7D/.gitignore#L37). Is there anything I am missing to reproduce this case?
