### ISSUE TITLE
 fix: launchMode issue while using deeplinks on Android

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/very_good_core#296]
Originally by @gonzalogauto

**Description**
After adding support for deep links in my app following the official [docs](https://docs.flutter.dev/ui/navigation/deep-linking) without doing any changes to the AndroidManifest.xml file on Android, seems that the default behaviour on some devices is open a new instance of the app even if the app is already running. Seems that the issue is caused by `android:launchMode` flag in the AndroidManifest.xml file, which in the `very_good_core` template defaults to `singleTop`. After searching about this issue I found that most people recommend to change that to `singleTask`. This solved the issue but seems that is not recommended by the android team [here](https://developer.android.com/guide/topics/manifest/activity-element?hl=es-419#lmode). IDK if this is something that needs to be solved first in the Flutter repo or not but seems to be something important to keep an eye on.
Just for now I'm using `launchMode:singleTask`, with `singleTop` or `standard` the problem appears again.

**Steps To Reproduce**

1. Setup deeplinks on Android using the official docs mentioned before.
2. Open a deeplink an that should open a second instance of the app.

**Expected Behavior**
Open a deeplink should not open a second instance of the app on Android devices.

**Screenshots**
- In this video you will see that tapping on a link opens a third instance of the app because we already had a second instance open (sorry I don't have it in the video).

**Additional Context**
Related issues reported here:
- [flutter](https://github.com/flutter/flutter/issues/110928).
- [flutter](https://github.com/flutter/flutter/issues/76856)
- [image_picker](https://github.com/flutter/packages/pull/3759).

Please LMK if you need more information.

**Comment by tomarra** [comment]
@gonzalogauto I'm assuming you ended up fixing this in the CIEE project. Would you be able to contribute that fix back to the template to close this out?

**Comment by gonzalogauto** [comment]
> @gonzalogauto I'm assuming you ended up fixing this in the CIEE project. Would you be able to contribute that fix back to the template to close this out?

Sure! I just sent the fix https://github.com/VeryGoodOpenSource/very_good_core/pull/297. 🚀
